### ISSUE TITLE
Implement `onlyProxy` on the upgradable contracts

### ISSUE THREAD

**Issue by Abhishekkochar** [WavesHQ/quantum#160]
#### What would you like to be added:
As per title, we should implement the `onlyProxy` from https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/UUPSUpgradeable.sol#L38-L42

This will act as a safeguard for the user experience, ensuring that they are only interacting with the bridge through the proxy instead of the implementation contract.

**Comment by cuongquangnam** [comment]
Close issue as I don't see it as a threat now
