### ISSUE TITLE
TX / Bridge History and more

### ISSUE THREAD

**Issue by Niceday310** [WavesHQ/quantum#589]
Dear Birthday Research Team,

here is what I found during testing. Thanks for your continuous development! 🚀

1) Percent buttons don't work

2) If you press "Verify" and the TX has not yet been confirmed, Error #4 appears, the explanation for this:

This is **"**Solution:** Please make sure you have funds in your wallet and have sent them over to the verification address to complete this transaction."*

--> It should be mentioned that the TX must already be confirmed before clicking the "Verify Button".

3) I think a TX/Bridge history is absolutely necessary here. A possibility to call up old TX again in order to be able to claim. With a note that it doesn't automatically end up in the metamask. With other bridges (synapse protocol) I don't have to claim anything, it comes directly to the right chain in the wallet in a TX.

For example, I didn't know that I had to claim the coins on the ETH side with a new TX, closed the Quantum bridge (the tab) and now I see no way to claim my coins on the ETH side, but they have already been sent from the lightwallet. ..

are these lost forever or how do I get to the claim page of this TX?

--> TX/Bridge History, Recover Button, Pending TX or similar and the reference to the claim

4) If you send too much/too little funds (from Defichain to ETH), you cannot claim them and they seem lost (as in point 3), there is no way to reclaim/reverify/edit.

**Comment by virgchiniwala** [comment]
Hi @Niceday310 thanks for getting in touch! 

We've fixed 1, do let us know if you face any issues. 

We're actively working on improvements for 2 and 4 - which should be reflected soon on Quantum. 

For 3 (TX History) - Thanks for the suggestion! We will explore this with the product team to ascertain the feasibility of implementing it

If you do have any further feedback, feel free to reach out to us below:
[https://forms.gle/RecvGj3RTgVMseCr6](url)

**Comment by Niceday310** [comment]
Thank you so much @virgchiniwala 🙏🏼
