### ISSUE TITLE
Brave: ETH `MAX` output = insufficient funds

### ISSUE THREAD

**Issue by izzycsy** [WavesHQ/quantum#595]
```
Ver: 0.18.0
Network: TestNet
Flow: ETH → DFC (only applies to ETH)
Description: Error after 65 confirmations 
```

**Actual:** 
On Brave browser, `%` buttons work as expected, selecting `MAX` > error: Insufficient Funds (only applies to ETH)

**Expected:** 
`25%`, `50%`, `75%`, `MAX` should display the respective outputs 

**To reproduce:** 
1. Select Source Network: Ethereum
2. at **Token**, select ETH → dETH
3. At **Amount to transfer**, select `MAX` > `error:` Insufficient Funds > note: available amount

![230228 - MAX incorrect output1](https://user-images.githubusercontent.com/65014479/221797339-29f5bc9b-6728-42f5-8136-29d2c9586955.png)

**Comment by pierregee** [comment]
quick input buttons is fixed on PR-592, but the max is not yet fixed
